### ISSUE TITLE
Did You Mean suggestions / misspelling intelligence

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/obento#148]
Two different things here:  
* suggestions / autocomplete, 
* "did you mean" spelling corrections

**Comment by kerchner** [comment]
There are really two possibilities here:  Autocomplete, versus "did you mean" on the results page.

@MustafaDasorwala recommends looking into "tries".

**Comment by kerchner** [comment]
Can (or does) the Summon API return "Did you mean" suggestions in the response json?

**Comment by lwrubel** [comment]
I found this: http://api.summon.serialssolutions.com/help/api/search/response/did-you-mean-suggestions, and see it as a field in currently returned searches. But not sure what the thresholds are as described in the documentation.

**Comment by kerchner** [comment]
Use case for testing:  "LaPalobara Weiner Political Parties Development" returns zero results in Bento, but "Did You Mean" in Summon suggests a spelling correction of "LaPalo***m***bara Weiner Political Parties Development" which yields much better results.
