### ISSUE TITLE
UI Jump To Menu for Handheld

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/obento#278]
The anchor titles in the current 'jump to' menu items in handheld appear above the fold for certain categories (databases, journals) when Best Bets are hidden.

**Comment by StudioZut** [comment]
Change the anchors to ids and... profit!

**Comment by StudioZut** [comment]
This is with the new card design, but the important part is that the "jump" shows the section title (Databases) and is no longer cut off:
![screen shot 2016-01-08 at 4 50 19 pm](https://cloud.githubusercontent.com/assets/1031373/12210485/5a2ffeac-b628-11e5-8f7c-bc94081f0deb.png)

**Comment by kerchner** [comment]
Fixed in #355
