### ISSUE TITLE
Databases "more" link - clicking causes description text to overlap with title

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/obento#294]
Before clicking "more" to expand:
![before-more](https://cloud.githubusercontent.com/assets/3451175/5551097/1ce54f5e-8b89-11e4-8eec-05f5c4b08ca5.png)

After clicking "more" to expand:
![after-more](https://cloud.githubusercontent.com/assets/3451175/5551098/206f3a72-8b89-11e4-95e5-0b20c3347a72.png)

**Comment by MustafaDasorwala** [comment]
we will have to debug this on production server as well since the bug doesn't show up on local system

**Comment by kerchner** [comment]
@MustafaDasorwala and @kerchner noticed that this is only occurring within the Drupal page (on both library test and prod) - talk to @StudioZut !

**Comment by StudioZut** [comment]
Likely a conflict with the Libsite7 theme css, will investigate.

**Comment by kerchner** [comment]
@StudioZut @MustafaDasorwala I think this may be the style that's at issue:
1.  Go to http://library.gwu.edu/search-all?query=science&ignoresearch=true
2.  Click "more" on the first database result
3.  Inspect Element on the database description paragraph
You'll note that it seems to have a margin-top that's negative - it's -.8em
```
media="all"
p + p, p + ul {
margin-top: -.8em;
}
```
Changing margin-top to 0 restores the space between the description and the title.

@StudioZut - hoping you can take it from here...

**Comment by StudioZut** [comment]
That looks like it @MustafaDasorwala, thanks! The css is in the Libsite Theme, I'll make the change and report back.

**Comment by StudioZut** [comment]
Fixed.

**Comment by kerchner** [comment]
FIxed by @zut in:  https://github.com/gwu-libraries/Libsite-Theme/commit/af9a859f95f418e5a865d83949f551204f63b40e   and deployed to prod and test.
