### ISSUE TITLE
Drupal site search api field value

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/obento#308]
It looks like the value for 'field' that I was using should in the api be changed from 'none' to 'nid'. 

Example:
https://library.gwu.edu/api/search/retrieve.json?keys=acm&fields=nid 
(instead of https://library.gwu.edu/api/search/retrieve.json?keys=acm&fields=none)

The current 'field=none' is throwing an error in the Drupal php logs because there is no node field named 'none'...

This will only impact the json output by replaced the invalid node field "none" with the valid node field "nid".

**Comment by kerchner** [comment]
@StudioZut is this the root cause of #259?

**Comment by StudioZut** [comment]
Not related, which sadly leaves #259 unresolved.

**Comment by StudioZut** [comment]
@MustafaDasorwala working on the test server now (Drupal/php log no longer throws the error), thanks!
