### ISSUE TITLE
Available Online Button

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/obento#317]
As a first step towards "buttonizing" the "Full Text Online" link in the Bento results, can you wrap the text and icon in a div with class "button-bento"

Currently: <i class="fa fa-book" title="Full Text Available Online"></i>Full Text Online

Change to <div class="button-bento"><i class="fa fa-book" title="Full Text Available Online"></i>Full Text Online</div>

The class doesn't exist yet, but this will make it easy to add styling as needed.

**Comment by StudioZut** [comment]
A mockup of how this might look with the new button design we're working on for Launchpad
![screen shot bento with book icon](https://cloud.githubusercontent.com/assets/1031373/6623549/06b5a83c-c8ba-11e4-9f78-c2a27d442cfb.png)

**Comment by kerchner** [comment]
Looks great!

**Comment by lwrubel** [comment]
@StudioZut see the branch in the pull request for this ticket, #330 . I made some steps toward shifting it to the launchpad style button, but there are some lingering issues. Specifically, font size and fa-book not level with the text. Would you take a look at the code?

**Comment by StudioZut** [comment]
I should be able to get that tidied up this week

**Comment by StudioZut** [comment]
@lwrubel is there a dev bento instance running this branch that I can point to?

**Comment by StudioZut** [comment]
When it displays within the Libraries site it inherits the Libraries button styling (needs a tiny margin-top adjustment but otherwise is "as intended"):
![screen shot 2016-01-20 at 2 48 45 pm](https://cloud.githubusercontent.com/assets/1031373/12461093/1a5b987a-bf85-11e5-83e2-47d7571a88e6.png)
Which brings up a larger issue! We have two front ends, one within the Libraries site and the other on the bento server itself. The new "card view" design, for instance, will only display on the Libraries version.
I'll adjust the button on the bento version to match and we can discuss the "twin fronts" later.

**Comment by StudioZut** [comment]
Made changes to obento.css to match the button (commit ac704c8):
![screen shot 2016-01-20 at 4 04 26 pm](https://cloud.githubusercontent.com/assets/1031373/12463055/87d49514-bf8f-11e5-9192-2707117777fc.png)
