### ISSUE TITLE
Selected queries are often resulting in a stack trace error via Articles box

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/obento#322]
We do not have a stack trace in the error messages; will have to get those from a dev instance.

Examples of queries failing consistently:
walmart
postcolonial melancholia
boudica and rome english origins
Mycobacterium tuberculosis

**Comment by dchud** [comment]
I'd argue these are two issues - first, that the stack trace isn't being shown, then, whatever issue(s) the stack traces reveal.

**Comment by kerchner** [comment]
Agreed - the comment above was noting that while a stack trace would be normal to include in the ticket, there is none to include in this case.

**Comment by kerchner** [comment]
This was determined to be a problem where the new (April 7) release of the Summon search API was not consistently including the ``['link']`` node in the results json.  As of 5:45 pm on April 8, ProQuest rolled back the new release.  Closing the issue.
