### ISSUE TITLE
Bento on gwlib-test is not returning from AJAX calls

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/obento#334]
This may(?) be related to upgrade of jquery version on gwlib-test.  This is important because jquery version upgrade is needed to support libsite accessibility fixes.

**Comment by StudioZut** [comment]
Bento is loading on my dev instance: http://gwdev-zut.wrlc.org/search-all?query=this
Just not on test: http://test.library.gwu.edu/search-all?query=this

The upgrade to jquery compatibility (1.10) is a separate issue: currently the search page in Drupal loads an older version of jquery (1.9.1) in order for bento to load, but this breaks the primary navigation menu behavior on that page.

**Comment by StudioZut** [comment]
Now that I can play with it on my dev box, it looks like it may be a simple jQuery noconflict issue. It might be fixed by wrapping all the scripts that get passed to index.php with
```
(function($) {
 // the existing jQuery code
})(jQuery);
```
Once I did that to the jQuery in index.php that page starts to work, it just needs to have that applied to all the jQuery that gets "ajaxed" into the page.

**Comment by StudioZut** [comment]
I wrapped the js in index.php in a function, which fixes the jquery conflict for that file but not for the included code pulled in via ajax. That's next!
Also, the master index.php file (and now the t334 branch) includes the save_data code that is causing the page to fail. I am testing using the index.php file from gwlibrary-prod.wrlc.org instead.

**Comment by StudioZut** [comment]
I wrapped all the the js in the template files in a function to avoid conflict. Running this from the gwbento-test and my dev machine:

http://gwdev-zut.wrlc.org/search-all?query=biology

The page loads and returns most of the results but generates this error in console:

GET http://gwbento-test.wrlc.org/databases_solr_html?q=this&ignoresearch=false&remote_addr=128.164.214.172 500 (INTERNAL SERVER ERROR)

**Comment by kerchner** [comment]
Reopening this issue - seems to be happening again.

**Comment by StudioZut** [comment]
This seems to be working now on test.library.gwu.edu, which is currently set to pull from the prod server http://gwbento-prod.wrlc.org:8080 in the libraries site config (https://test.library.gwu.edu/admin/config/content/catalog_pointer)

**Comment by kerchner** [comment]
Working on this as part of deploying SSL on test (https://github.com/gwu-libraries/obento/pull/377).  Seems that I'm having to add an extra `/` in index.php to construct the path properly (in the `fetch` function).  Not sure yet why this is different on test vs. prod.

**Comment by kerchner** [comment]
This is no longer occurring - likely resolved in the above comment.  Closing issue.
