### ISSUE TITLE
deselect the option Add results beyond the WRLC collection

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/obento#336]
When you click through to articlesplus from the bento search results, the option "Add results beyond the WRLC collection" is checked/selected. It would be preferable to have that option deselected.

**Comment by kerchner** [comment]
@cummingsm We can certainly do this, but I just want to double-check, as this may have been a conscious choice.  It looks like we initially chose for Catalog (Books & Media) results to be scoped to holdings-only, but for Articles results to include articles beyond WRLC collections.

Furthermore, it's currently inconsistent, as the article results count on the bento results page is the # of results limited to WRLC collections, whereas when you click through to Summon, it includes results beyond the collection (and the # is higher).  I think this inconsistency may have crept in with Summon 2.0.

Again, I'm fine with limiting to within-WRLC only, as long as there wasn't some rationale for it to be unlimited initially.

**Comment by kerchner** [comment]
note to self:  the ```s.ho``` parameter would need to be ```s.ho=t``` .  Summon seems to ignore ```s.cmd= setHoldingsOnly(true)```
