### ISSUE TITLE
Drupal search is indexing js in body

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/obento#368]
Drupal is indexing script tags inside the Body, which includes all js in the index.php bento file. This is the default behavior for Drupal (it expects js to be limited to the Head). 
The simplest solution is to wrap any js in a comment. This will prevent it from being indexed, but like all js on a page the script itself is exposed and can be viewed in the page source. We will have to address any security implications separately.

**Comment by StudioZut** [comment]
Another non-technical fix is to place any scripts below the content.

**Comment by kerchner** [comment]
@StudioZut would every indexed page on the entire Drupal site containing JavaScript require this fix (regardless of which method of fix described above) ?

**Comment by StudioZut** [comment]
Yes, for all pages with js in the page content field. Only a few of our pages are customized like this. More often there's a css <style> tag in the content field for custom styling. Neither of those are best practice and Drupal expects that to be done in the theme, not dropped into the page content.

**Comment by kerchner** [comment]
Examples:
- http://library.gwu.edu/search-all?query=function
Returns:
```
 Search

function formFeedback() { // TEST form - uncomment for TEST ... } (function($) { var searchid; var data; var ignoresearch; var count; var bento_url; var remote_addr = "184.73.193.107"; function fetch(vals){ if(count == "0" || ...

Library Instruction Statistics Form

jQuery( document ).ready(function() { jQuery('#edit-submitted-session-session-type').change(function() { if (jQuery(this).val() === 'ses_type_orientation') { ...
```
(same results - and more - via http://library.gwu.edu/search/node/function)

- http://library.gwu.edu/search-all?query=var
```
 Search

... { // TEST form - uncomment for TEST var formID = "1YNODxi35XiJEv80wOJDFV3H2IIfOYmU3K5hCU8SfunE"; // PRODUCTION form - uncomment for PRODUCTION // var formID = "1zTbNA6_4urOuEAjcCJrGBqZD8JVY3xxqTIaHP44YHOA"; var ...

Eckles Library Summer Hours

... solid #ccc;} .paddingBlock h3 {margin-top:0.5em;} } var days = ['#su', '#mo', '#tu', '#we', '#th', '#fr', '#sa']; var now = new Date(); var today = days[ now.getDay() ]; jQuery(function($) ...
```

(same results - and more - via http://library.gwu.edu/search/node/var)
