### ISSUE TITLE
Some Articles items with hasFullText=true are linking to 360link (/findit)

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/obento#389]
An example:  search on "Composable scheduler activations for Haskell" which should yield a single result.

The item's hasFullText=true, but the serialssolutions URL (http://gw.summon.serialssolutions.com/2.0.0/link/0/eLvHCXMwpV1LS8NAEF6KeBDEt1gfkIMncYt57WaPQaot2gc1KvZSkuxuD9ZW-rB_39ndJK0WQfESShIGujOZ-XYe3yJ0zqmd2vxKYs6oi72E-5hBmMdC2jRlPKFOqglMu97jrXffZbelUt7_ZAq1RcKtPzcbxf7o38qFe6BeNSz7BwUXQuEG_AY1wxUUDddfqVp906OJnoGCvSr8k4EYa5KMj6zPTbUS1uLJqxgMfgCjNxDesqxg23RsveUxTaVf6k9hB7zzXaf-UGuGujPgrrJIsNbCDjzRql-aIQs7961nnV2tN1pFxaddfYlaqnGwWX34-jDLPZihyCJ9SDBl5kicijDOE7bamBJD_pt7VzMPv-KoM3YnJUZJsYmuqdqLqJRX4r8Fq6KF0HSn0d6KCEUn4BJ1ikfEGkVQho1wkNMuqrfzArdmD_8m4QtEWVfTQbPJEuiIdtBWpiArNDrfRSUx3EPb-UkcVuaY99HlwgSswgSsJROwwASszAQOUHRTja5rODsHA6eEBFhxNgIOI4IkklPYTl8xmkqf24wyJxYydTg4Uof5DNApcYSMAZSxRDKAlgD4bPcQbcZqXGI41WOV_AhZiXRpQgI3kZJ7biAYgBnhejHgfT_2U1ZGF_kS9N4N7UnvxxUvoyOzSMWrisM_cMG1H_9FzgnaUEZmElynaG06nokzVOrPPwEq4EoO)

resolves to an item page in findit:

http://findit.library.gwu.edu/go?ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fsummon.serialssolutions.com&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.genre=article&rft.atitle=Composable+scheduler+activations+for+Haskell&rft.jtitle=Journal+of+Functional+Programming&rft.au=SIVARAMAKRISHNAN%2C+K.+C&rft.au=HARRIS%2C+TIM&rft.au=MARLOW%2C+SIMON&rft.au=PEYTON+JONES%2C+SIMON&rft.date=2016&rft.issn=0956-7968&rft.eissn=1469-7653&rft.volume=26&rft_id=info:doi/10.1017%2FS0956796816000071&rft.externalDBID=n%2Fa&rft.externalDocID=10_1017_S0956796816000071

The desired result in this case would be to resolve instead to the full text link shown in the launchpad page:

http://findit.library.gwu.edu/log?L=UZ4UG4LZ9G&D=T9M&J=JOUROFFUNPR&P=Link&PT=EZProxy&U=http%3A%2F%2Fproxygw.wrlc.org%2Flogin%3Furl%3Dhttp%3A%2F%2Fwww.journals.cambridge.org%2Fabstract_S0956796816000071

or, to where it resolves:

http://journals.cambridge.org/action/displayAbstract?fromPage=online&aid=10379784&fileId=S0956796816000071

**Comment by kerchner** [comment]
This may be an example of what #149 was referring to.

**Comment by lwrubel** [comment]
This is normal behavior for Summon. For some journal publishers, it has in its index a direct link to the publisher's site. In other cases, it knows we have full text for an article (based on Knowledgebase activations) and links to 360 Link for the resolution of the link. The native Summon interface does the same thing. (There are some 360 Link configurations we might explore, as a larger project.)

**Comment by kerchner** [comment]
Summon's result includes an openURL value for (most?) items with full text available; for example:

`openUrl: "ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fsummon.serialssolutions.com&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.genre=article&rft.atitle=Composable+scheduler+activations+for+Haskell&rft.jtitle=Journal+of+Functional+Programming&rft.au=SIVARAMAKRISHNAN%2C+K.+C&rft.au=HARRIS%2C+TIM&rft.au=MARLOW%2C+SIMON&rft.au=PEYTON+JONES%2C+SIMON&rft.date=2016&rft.issn=0956-7968&rft.eissn=1469-7653&rft.volume=26&rft_id=info:doi/10.1017%2FS0956796816000071&rft.externalDBID=n%2Fa&rft.externalDocID=10_1017_S0956796816000071"`

This value can be resolved to the item's URL by appending to `http://uz4ug4lz9g.openurl.xml.serialssolutions.com/openurlxml?version=1.0&`

@lwrubel notes that the openURL resolution is less reliable than resolving directly through Summon where possible, so the latter should be preferred when available.  However, this will require something along the lines of resolving the Summon URL (perhaps using `requests` follow URL) to determine whether it either A) resolves to findit.library.gwu.edu, in which case we prefer to construct and provide the openURL link in the Bento result, or B) resolves directly to the item (anything but findit.library.gwu.edu) in which case we use this as we're currently doing.
