### ISSUE TITLE
HTTPS support 

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/obento#414]
Bento needs to runs with HTTPS to support the library's site as a whole being on HTTPS.

**Comment by kerchner** [comment]
Must be completed before Chrome starts flagging non-https sites as insecure, in October 2017

**Comment by kerchner** [comment]
See #230 - this work may already be completed.  In this ticket (#414) we will be verifying that SSL deployment works.

**Comment by kerchner** [comment]
Completed and deployed as per the apache config file template created in #230 (thank you @adityadharne !)
