### ISSUE TITLE
load_databases needs update for changes in libguides A-Z database list page

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/obento#426]
As a result, the databases have become out of date.

- Throwing security exception due to site certificate claiming to be from libguides.com (vs. libguides.gwu.edu).
   - Fixed this on the test instance by upgrading Python to 2.7.9 and explicitly using this in the virtualenv
- Page is now returned as HTML, not JSON, and page structure *may* have changed.  BeautifulSoup scraping may need updates.

**Comment by kerchner** [comment]
The issue is further compounded by the fact that the page now uses jQuery to load the contents, so `response.get()` only gets the page before the Javascript/jQuery has run and populated the contents.  Fixing this may require use of a headless, but javascript-capable browser, unless there is another way to access the libguides database list.  Assuming there is no API, but it might be worth double-checking this.

**Comment by kerchner** [comment]
To install Python 2.7.9.  As noted above, this will resolve the security issue, but will not address the fact that the page to be scraped has become much more javascript-driven.

I also had to apt-get purge, and reinstall, all of the python tools etc. to "clear out" the pip-installed packages.  Not sure if that is necessary.

```
wget https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
tar xfz Python-2.7.9.tgz
cd Python-2.7.9/
./configure --prefix /usr/local/lib/python2.7.9
make
make install  # may require sudo
```
Test if the version works

```
/usr/local/lib/python2.7.9/bin/python -V
Python 2.7.9
```

You can then create a new virtualenv as follows:
`virtualenv ENV --python=/usr/local/lib/python2.7.9/bin/python`

Activate the virtualenv, and verify `python -V`

**Comment by chrisgg** [comment]
As an alternative to scraping the database list, we can export its contents
in .csv format from Libguides admin. Unfortunately the export part can't be
automated. If you're interested in pursuing that option, let me know!

**Comment by kerchner** [comment]
Incidentally, it seems that upgrading to Python 2.7.9 was not necessary, at least when deploying to gwbento-test-14 and gwbento-prod-14.
